mode: weixincp # 设置企业微信推送（serverChan:server酱,weixincp：企业微信）
sckey: # 仅需填写mode相关配置即可，如填写mode为weixincp，那么sckey不用填写
corpid: xxxxx
corpsecret: xxxxx
agentid: xxxxx
cron: '0 0 0 11 * ?' # simple可无视该配置
account:
  - cookie: cookie1
    stuid: stuid1
    stoken: stoken1
    toUser: toUser1 # 这里为空时候，默认向所有人发送
  - cookie: cookie2
    stuid: stuid2
    stoken: stoken2
    toUser: toUser2
